# markdown: kramdown
# kramdown:
#     math_engine: katex
title: Optimal Scalling of Data Center
tagline: Easy websites with GitHub Pages
description: Minimal tutorial on making a simple website with GitHub Pages

use_math: true
markdown: maruku
# # Markdown Processing
# kramdown:
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false
#   math_engine: katex
